name: test_codelab
description: How to test a flutter app codelab

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0            # new

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:           # new
    sdk: flutter              # new
  test: ^1.14.4               # new

#  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true